// backend/src/lib/components/TextInput.svelte
<script lang="ts">
	export let id: string;
	export let label: string;
	export let name: string;
	export let value: string = '';
</script>

<div class="text-input">
	<label for={id}>
		{label}
	</label>
	<input type="text" {id} {name} required bind:value />
</div>

<style lang="postcss">
	.text-input {
		width: 100%;
		max-width: theme(maxWidth.xs);
	}
	label {
		color: theme(colors.neutral.600);
		font-size: theme(fontSize.base);
		font-weight: theme(fontWeight.medium);
	}
	input {
		display: block;
		height: theme(space.10);
		width: 100%;
		margin: auto;
		margin-top: theme(space.1);
		padding: theme(padding[0.5]) theme(padding.2);
		box-sizing: border-box;
		border: 1px solid theme(colors.neutral.300);
		@apply rounded;
		background: theme(colors.neutral.50);
		color: theme(colors.neutral.700);
		font-size: theme(fontSize.base);
	}
</style>

// frontend/src/components/TextInput.tsx
type Props = {
  id: string;
  name: string;
  label: string;
  value?: string;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void;
};

export function TextInput({ id, name, label, value, onChange }: Props) {
  return (
    <div className="max-w-xs w-full">
      <label htmlFor={id} className="text-neutral-600 text-base font-medium">
        {label}
      </label>
      <input
        type="text"
        id={id}
        name={name}
        required
        className="block h-10 w-full py-0.5 px-2 mx-auto mt-1 box-border border border-solid border-neutral-300 rounded bg-neutral-50 text-neutral-700 text-base"
        value={value}
        onChange={onChange}
      />
    </div>
  );
}
export default TextInput;
