// frontend/src/components/Button.tsx
type Props = {
  children: React.ReactNode;
  onClick?: () => void;
  compact?: boolean;
};

export default function Button({ children, compact, onClick }: Props) {
  const padding = compact ? "px-4 py-2" : "px-6 py-3";
  return (
    <button
      className={`flex-inline items-center justify-center ${padding} border-transparent rounded-lg bg-ess-orange text-neutral-50 font-bold text-sm hover:cursor-pointer`}
      onClick={onClick}
    >
      {children}
    </button>
  );
}

// backend/src/lib/components/Button.svelte
<script lang="ts">
	export let compact: boolean = false;
</script>

<button
	class:compact
	class:px-4={compact}
	class:py-2={compact}
	class:px-6={!compact}
	class:py-3={!compact}
	on:click
>
	<slot />
</button>

<style lang="postcss">
	button {
		padding: theme(space.3) theme(space.6);
		display: flex-inline;
		align-items: center;
		justify-content: center;
		border-color: transparent;
		border-radius: theme(borderRadius.lg);
		background-color: theme(colors.ess-orange);
		color: theme(colors.neutral.50);
		font-weight: theme(fontWeight.bold);
		font-size: theme(fontSize.sm);
	}
	button.compact {
		padding: theme(space.2) theme(space.4);
	}
	button:hover {
		cursor: pointer;
	}
</style>
