// frontend/src/components/Button.tsx
type Props = {
  children: React.ReactNode;
  onClick?: () => void;
  compact?: boolean;
};

export default function Button({ children, compact, onClick }: Props) {
  const padding = compact ? "px-4 py-2" : "px-6 py-3";
  return (
    <button
      className={`flex-inline items-center justify-center ${padding} border-transparent rounded-lg bg-ess-orange text-neutral-50 font-bold text-sm hover:cursor-pointer`}
      onClick={onClick}
    >
      {children}
    </button>
  );
}

// src/lib/components/Button.svelte
<script lang="ts">
  import Loading from "./Loading.svelte";

  export let compact = false;
  export let loading = false;
</script>

<button class:compact class:loading on:click>
  <div class="spinner">
    <Loading size="1.5rem" />
  </div>
  <slot />
</button>

<style lang="postcss">
  button {
    padding: theme(space.3) theme(space.6);

    position: relative;
    display: inline-flex;
    align-items: center;
    justify-content: center;

    border-color: transparent;
    border-radius: theme(borderRadius.lg);
    color: theme(colors.neutral.50);
    background-color: theme(colors.ess-orange);

    font-weight: theme(fontWeight.bold);
    font-size: theme(fontSize.sm);
  }
  button:hover {
    cursor: pointer;
  }
  .compact {
    padding: theme(space.2) theme(space.4);
  }
  .loading {
    color: transparent;
  }
  div {
    display: none;
  }
  .loading > div {
    position: absolute;
    inset: 0;
    display: inline-flex;
    align-items: center;
    justify-content: center;
  }
</style>
